services:
  db:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_PASSWORD: app12345@
      POSTGRES_USER: app
      POSTGRES_DB: isa_stats
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
